### ISSUE TITLE
Error when syncing mdn/content with main: Run failed at startup: Lock old issues and pull requests

### ISSUE THREAD

**Issue by tlylt** [mdn/workflows#113]
## Problem Description
When I perform an update branch action via the GitHub UI to sync my fork with the latest main,
> ![image](https://user-images.githubusercontent.com/41845017/210903440-8bdffceb-2843-4253-96fe-8324e16a6d2a.png)

I am notified that a workflow run has failed to startup (e.g. https://github.com/tlylt/content/actions/runs/3851298925)
> ![image](https://user-images.githubusercontent.com/41845017/210903703-49c23ed1-c916-4250-87d5-a27d3edaeab9.png)

An email notification will also be sent, which is slightly annoying.

## Expected outcome

The workflow (Lock old issues and pull requests) should work well for forks
- either by making sure that it works on forks
- or skip the run for forks

P.S. I am happy to help fix this if necessary!

**Comment by bsmth** [comment]
Interesting, I guess it shouldn't be run because we have a check using `input` that points to only the `mdn/content` repo: https://github.com/tlylt/content/blob/main/.github/workflows/lock-closed.yml#L10

But the error is raising permissions warnings before that.

Note that others use something like the following:

https://github.com/apache/iceberg/pull/3500/files

```yaml
jobs:
  publish-snapshot:
    if: github.repository_owner == 'apache'
```

**Comment by bsmth** [comment]
Another thing is this action is skipped on my fork: https://github.com/bsmth/content/actions/runs/3851302133

**Comment by tlylt** [comment]
Hi @bsmth, as you mentioned I think it should already be skipping for forks....Could you help check if the following setting for your fork is different from mine? If so this is probably the reason that the action is failing from start-up, hence didn't reach the skipping part.
![image](https://user-images.githubusercontent.com/41845017/211015222-f10016f9-131d-4dc9-940f-e2ca4f06f389.png)

**Comment by bsmth** [comment]
Yeah that looks like the problem, it should have read and write permissions, which should be default. You can try enabling this to see if it fixes the problem

**Comment by tlylt** [comment]
> Yeah that looks like the problem, it should have read and write permissions, which should be default. You can try enabling this to see if it fixes the problem

Got it, seems to [work](https://github.com/tlylt/content/actions/runs/3859369515) now that I changed it to read and write permissions. Not sure why the permission defaulted to the second one as I don't recall configuring it.

Thanks for checking!
