### ISSUE TITLE
Merge conflict workflow creates lots of comments

### ISSUE THREAD

**Issue by bsmth** [mdn/workflows#120]
The "rebase needed" workflow creates a lot of comments:

![image](https://user-images.githubusercontent.com/43580235/222711322-5b6bdae9-5381-4fd7-8d2f-6eeb5e59380d.png)

It would be nice to have one of the following options:
* editing the existing comment if it's outdated (sticky comment?)
* minimize the comment

__other notes:__
* "Sticky pull request comment" - https://github.com/marocchino/sticky-pull-request-comment/blob/main/action.yml
* Source of the action see https://github.com/eps1lon/actions-label-merge-conflict/blob/main/sources/main.ts

**Comment by caugner** [comment]
The screenshot shows a PR with a lot of files, so in that case the comment/notification can be annoying, but overall I think the comment is helpful, because it causes a notification - in contrast to the labeling.

**Comment by bsmth** [comment]
I find it a bit excessive but:

>the comment is helpful, because it causes a notification

that's reasonable, and I can live with it 😄, closing as `wontfix`

**Comment by bsmth** [comment]
@caugner just a reminder we spoke about this in the community call this week where some reviewers see multiple comments as an indicator of PR activity and may assume it's being looked at. I wonder if we should just disable the comments altogether. 🤔
