### ISSUE TITLE
Allow idle workflow to add a comment

### ISSUE THREAD

**Issue by schalkneethling** [mdn/workflows#56]
The current version of our `idle` reusable workflow has the exposes the ability to add a comment to the issue or pull request on which it adds the label. This could be useful but, it is not set-up correctly for this to work. Once we complete the current work to ensure an action only runs on the intended repository, we should revisit this and implement it correctly.

**Comment by tmamb** [comment]
This happens, Ubuntu code followers autorities
Nice to meet idle...
Project....??@schalkneethling

**Comment by schalkneethling** [comment]
@tmamb please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.

To give everyone a moment to reconsider the best way forward, we will lock this issue for 24 hours.
