### ISSUE TITLE
PR Test workflow error when fetching from main

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/workflows#59]
[danielhjacobs/content] PR Test workflow error

An error occurred trying to start process '/home/runner/runners/2.291.1/externals/node16/bin/node' with working directory '/home/runner/work/content/content'. Argument list too long

https://github.com/danielhjacobs/content/runs/6633249535?check_suite_focus=true

**Comment by schalkneethling** [comment]
> [danielhjacobs/content] PR Test workflow error
> 
> An error occurred trying to start process '/home/runner/runners/2.291.1/externals/node16/bin/node' with working directory '/home/runner/work/content/content'. Argument list too long
> 
> https://github.com/danielhjacobs/content/runs/6633249535?check_suite_focus=true

I see this failed on your fork of the `content` repo. As you know, we are in the process of only running workflows on the target repo so this should resolve itself in a few days.
