### ISSUE TITLE
Release please has dropped support for node 12

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/workflows#85]
Release please dropped support for node 12 in version 14. However that is set as default node version in this repo workflows.

Release notes https://github.com/googleapis/release-please/releases/tag/v14.0.0

File in question https://github.com/mdn/workflows/blob/main/.github/workflows/publish-release.yml

I don't know if this actually causes problems. But there is at least this problem https://github.com/mdn/bob/issues/913 that was reported.

Edit: nevermind, this repo uses different version :)

Edit2: Action version 3.5 updated release-please from v13 to v14 https://github.com/google-github-actions/release-please-action/blob/main/CHANGELOG.md

**Comment by schalkneethling** [comment]
> Release please dropped support for node 12 in version 14. However that is set as default node version in this repo workflows.
> 
> Release notes https://github.com/googleapis/release-please/releases/tag/v14.0.0
> 
> File in question https://github.com/mdn/workflows/blob/main/.github/workflows/publish-release.yml
> 
> I don't know if this actually causes problems. But there is at least this problem [mdn/bob#913](https://github.com/mdn/bob/issues/913) that was reported.
> 
> Edit: nevermind, this repo uses different version :)
> 
> Edit2: Action version 3.5 updated release-please from v13 to v14 https://github.com/google-github-actions/release-please-action/blob/main/CHANGELOG.md

@rubiesonthesky Thank you for bringing this to our attention. Are any of these items still an issue? I believe we targetNodejs v16 and it looks like Dependabot has updated everything to the latest versions.
